#pragma once
#include <wx/wx.h>
#include <vector>
#include <cassert>
#include <memory>
#include <array>
#include <iosfwd>
#include <string>
#include <cmath>
#include <iostream>
#include <ostream>
#include <sstream>
#include <stdexcept>
#include <cstdlib>
#include <cmath>